export { default as Tabs } from './Tabs'
export { default as TabsList } from './TabsList'
export { default as TabsContent } from './TabsContent'
export { default as TabsListItem } from './TabsListItem'
export { default as TabsView } from './TabsView'
