export const list = [
  { value: 'apple', label: 'Apple', disabled: true },
  { value: 'banana', label: 'Banana', disabled: true },
  { value: 'kiwi', label: 'Kiwi' },
  { value: 'peach', label: 'Peach', disabled: true },
  { value: 'grape', label: 'Grape' },
  { value: 'aloe', label: 'Aloe' },
  { value: 'apple2', label: 'Apple2' },
  { value: 'banana2', label: 'Banana2', disabled: true },
  { value: 'kiwi2', label: 'Kiwi2' },
  { value: 'peach2', label: 'Peach2', disabled: true },
  { value: 'grape2', label: 'Grape2' },
  { value: 'aloe2', label: 'Aloe2' },
  { value: 'apple3', label: 'Apple3' },
  { value: 'banana3', label: 'Banana3', disabled: true },
  { value: 'kiwi3', label: 'Kiwi3' },
  { value: 'peach3', label: 'Peach3', disabled: true },
  { value: 'grape3', label: 'Grape3' },
  { value: 'aloe3', label: 'Aloe3' },
]
