name: 'Chromatic Deployment'

on:
  push:
    branches: [main]
    paths:
      - 'playground/**.stories.tsx'
  pull_request:
    branches: [main]
    paths:
      - 'playground/**.stories.tsx'

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: pnpm install --filter playground...
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDirectory: playground
